import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Heart, AlertCircle, Trash2 } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useCars } from '../contexts/CarContext';
import { formatCurrency } from './Overview';
export const Wishlist = () => {
    const { user, setShowLoginModal } = useAuth();
    const { wishlistCars, handleToggleWishlist, setActiveTab, openCarDetails, setSelectedForCompare } = useCars();
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("h2", { className: "text-2xl font-bold text-slate-900 flex items-center space-x-2", children: [_jsx(Heart, { className: "h-6 w-6 text-rose-500 fill-current" }), _jsx("span", { children: "Your Saved Wishlist" })] }), !user ? (_jsxs("div", { className: "glass-panel p-12 text-center space-y-4", children: [_jsx(AlertCircle, { className: "h-10 w-10 text-brand-600 mx-auto" }), _jsx("h4", { className: "font-bold text-slate-800", children: "Login required to view wishlist" }), _jsx("p", { className: "text-sm text-slate-500", children: "Save items directly to your profile database." }), _jsx("button", { onClick: () => setShowLoginModal(true), className: "px-5 py-2.5 rounded-lg bg-brand-600 text-white font-bold hover:bg-brand-500 text-xs shadow-sm", children: "Sign In" })] })) : wishlistCars.length === 0 ? (_jsxs("div", { className: "glass-panel p-12 text-center space-y-3", children: [_jsx(Heart, { className: "h-10 w-10 text-slate-400 mx-auto" }), _jsx("h4", { className: "font-bold text-slate-800", children: "Your wishlist is empty" }), _jsx("p", { className: "text-sm text-slate-500", children: "Start exploring vehicles to add candidates to your saved shortlist." }), _jsx("button", { onClick: () => setActiveTab('search'), className: "px-4 py-2 rounded-lg bg-slate-100 hover:bg-slate-200 border border-slate-200 text-xs font-semibold text-slate-700 transition", children: "Explore Catalog" })] })) : (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6", children: wishlistCars.map((car) => (_jsxs("div", { onClick: () => openCarDetails(car), className: "glass-card overflow-hidden hover-scale flex flex-col justify-between cursor-pointer", children: [_jsx("img", { src: car.images?.[0] ||
                                'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80', alt: car.model, className: "h-44 w-full object-cover border-b border-slate-100" }), _jsxs("div", { className: "p-4 space-y-3 flex-grow flex flex-col justify-between", children: [_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx("span", { className: "text-xs font-bold text-brand-600 uppercase tracking-wide", children: car.make }), _jsx("button", { onClick: (e) => {
                                                        e.stopPropagation();
                                                        handleToggleWishlist(car._id);
                                                    }, className: "text-slate-400 hover:text-red-500 transition p-1", title: "Remove from wishlist", children: _jsx(Trash2, { className: "h-4 w-4" }) })] }), _jsxs("h4", { className: "font-bold text-base text-slate-850", children: [car.model, ' ', _jsxs("span", { className: "text-xs font-normal text-slate-500", children: ["(", car.variant, ")"] })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 py-2 border-y border-slate-100 my-2 text-xs text-slate-550", children: [_jsxs("span", { children: ["\u26FD ", car.fuelType] }), _jsxs("span", { children: ["\u2699\uFE0F ", car.transmission] }), _jsxs("span", { children: ["\uD83D\uDE97 ", car.bodyType] }), _jsxs("span", { children: ["\uD83D\uDCC8 ", car.mileage, " km/l"] })] }), _jsxs("div", { className: "flex items-center justify-between pt-2", children: [_jsx("span", { className: "font-extrabold text-sm text-brand-600", children: formatCurrency(car.price) }), _jsxs("div", { className: "flex items-center space-x-1", children: [_jsx("button", { onClick: (e) => {
                                                        e.stopPropagation();
                                                        openCarDetails(car);
                                                    }, className: "px-3 py-1.5 rounded bg-slate-100 border border-slate-200 hover:bg-slate-200 text-slate-700 text-xs font-semibold", children: "Reviews" }), _jsx("button", { onClick: (e) => {
                                                        e.stopPropagation();
                                                        setSelectedForCompare((prev) => [
                                                            ...prev.filter((c) => c._id !== car._id),
                                                            car
                                                        ]);
                                                    }, className: "px-4 py-1.5 rounded bg-brand-50 border border-brand-200 text-brand-600 hover:bg-brand-100 text-xs font-semibold", children: "Compare" })] })] })] })] }, car._id))) }))] }));
};
//# sourceMappingURL=Wishlist.js.map