import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Sliders, AlertCircle, Heart, Scale, Star, MessageSquare } from 'lucide-react';
import { useCars } from '../cars/CarContext';
import { formatCurrency } from './Overview';
export const BrowseCars = () => {
    const { 
    // Catalog State
    cars, totalCars, currentPage, setCurrentPage, hasNextPage, loadingCars, searchKeyword, setSearchKeyword, 
    // Filters State
    filterBrand, setFilterBrand, filterModel, setFilterModel, filterFuel, setFilterFuel, filterTransmission, setFilterTransmission, filterMinPrice, setFilterMinPrice, filterMaxPrice, setFilterMaxPrice, filterPerformance, setFilterPerformance, filterSafetyRating, setFilterSafetyRating, filterSeatingCapacity, setFilterSeatingCapacity, filterMinYear, setFilterMinYear, filterMaxYear, setFilterMaxYear, filterMinMileage, setFilterMinMileage, sortBy, setSortBy, sortOrder, setSortOrder, priceError, brands, brandModels, fuelTypes, transmissions, seatingCapacities, safetyRatings, years, 
    // Actions
    selectedForCompare, wishlistIds, handleToggleWishlist, handleToggleSelectCompare, openCarDetails, applyFilters, resetFilters } = useCars();
    const handleSearchSubmit = (e) => {
        e.preventDefault();
        applyFilters();
    };
    const handleResetFilters = () => {
        resetFilters();
    };
    const renderCarActions = (car) => (_jsxs("div", { className: "flex items-center space-x-1", children: [_jsx("button", { onClick: (e) => {
                    e.stopPropagation();
                    openCarDetails(car);
                }, className: "p-2 rounded-lg border border-slate-200 hover:bg-slate-50 text-slate-500 transition", title: "View details & reviews", children: _jsx(MessageSquare, { className: "h-4 w-4" }) }), _jsx("button", { onClick: (e) => {
                    e.stopPropagation();
                    handleToggleSelectCompare(car);
                }, className: `p-2 rounded-lg border transition ${selectedForCompare.some((c) => c._id === car._id)
                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                    : 'border-slate-200 hover:bg-slate-50 text-slate-500'}`, title: "Compare Spec", children: _jsx(Scale, { className: "h-4 w-4" }) }), _jsx("button", { onClick: (e) => {
                    e.stopPropagation();
                    handleToggleWishlist(car._id);
                }, className: `p-2 rounded-lg border transition ${wishlistIds.includes(car._id)
                    ? 'bg-rose-50 border-rose-200 text-rose-600'
                    : 'border-slate-200 hover:bg-slate-50 text-slate-500'}`, children: _jsx(Heart, { className: "h-4 w-4 fill-current" }) })] }));
    return (_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-4 gap-8", children: [_jsxs("div", { className: "glass-panel p-5 lg:sticky lg:top-24 h-[calc(100vh-8.5rem)] flex flex-col justify-between overflow-hidden shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between pb-3.5 border-b border-slate-100 shrink-0 bg-white z-10", children: [_jsxs("h3", { className: "font-bold text-slate-800 flex items-center space-x-2", children: [_jsx(Sliders, { className: "h-5 w-5 text-brand-600" }), _jsx("span", { children: "Filters" })] }), _jsx("button", { onClick: handleResetFilters, className: "text-xs text-slate-500 hover:text-brand-600 transition", children: "Reset" })] }), _jsxs("div", { className: "flex-grow overflow-y-auto py-4 space-y-5 custom-scrollbar pr-1.5", children: [_jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Brand" }), _jsxs("select", { value: filterBrand, onChange: (e) => setFilterBrand(e.target.value), className: "w-full bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500", children: [_jsx("option", { value: "", children: "All Brands" }), brands.map((b) => (_jsx("option", { value: b, children: b }, b)))] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Model" }), _jsxs("select", { value: filterModel, onChange: (e) => setFilterModel(e.target.value), disabled: !filterBrand, className: "w-full bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500 disabled:opacity-50 disabled:cursor-not-allowed", children: [_jsx("option", { value: "", children: filterBrand ? 'All Models' : 'Select Brand First' }), filterBrand && brandModels[filterBrand] && brandModels[filterBrand].map((m) => (_jsx("option", { value: m, children: m }, m)))] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Fuel Type" }), _jsxs("div", { className: "grid grid-cols-2 gap-1.5", children: [_jsx("button", { onClick: () => setFilterFuel('Any'), className: `px-2 py-1.5 rounded-lg text-xs font-semibold border transition ${filterFuel === 'Any'
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: "Any" }), fuelTypes.map((f) => (_jsx("button", { onClick: () => setFilterFuel(f), className: `px-2 py-1.5 rounded-lg text-xs font-semibold border transition ${filterFuel === f
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: f }, f)))] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Transmission" }), _jsxs("div", { className: "grid grid-cols-3 gap-1", children: [_jsx("button", { onClick: () => setFilterTransmission('Any'), className: `py-1.5 rounded-lg text-[10px] font-semibold border transition ${filterTransmission === 'Any'
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: "Any" }), transmissions.map((t) => (_jsx("button", { onClick: () => setFilterTransmission(t), className: `py-1.5 rounded-lg text-[10px] font-semibold border transition ${filterTransmission === t
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: t }, t)))] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Min Safety Rating (NCAP)" }), _jsx("div", { className: "flex gap-1", children: [0, 3, 4, 5].map((stars) => (_jsx("button", { onClick: () => setFilterSafetyRating(stars), className: `flex-1 py-1.5 rounded-lg text-xs font-semibold border transition ${filterSafetyRating === stars
                                                ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: stars === 0 ? 'Any' : `${stars}★+` }, stars))) })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Seating Capacity" }), _jsx("div", { className: "flex gap-1.5", children: [0, 5, 7].map((seats) => (_jsx("button", { onClick: () => setFilterSeatingCapacity(seats), className: `flex-1 py-1.5 rounded-lg text-xs font-semibold border transition ${filterSeatingCapacity === seats
                                                ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                : 'border-slate-200 bg-white text-slate-660 hover:bg-slate-50'}`, children: seats === 0 ? 'Any' : `${seats} Seats` }, seats))) })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Model Year Range" }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsxs("select", { value: filterMinYear, onChange: (e) => setFilterMinYear(e.target.value), className: "w-1/2 bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none", children: [_jsx("option", { value: "", children: "Min" }), years.map((y) => (_jsx("option", { value: y, children: y }, y)))] }), _jsx("span", { className: "text-slate-450", children: "-" }), _jsxs("select", { value: filterMaxYear, onChange: (e) => setFilterMaxYear(e.target.value), className: "w-1/2 bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none", children: [_jsx("option", { value: "", children: "Max" }), years.map((y) => (_jsx("option", { value: y, children: y }, y)))] })] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsxs("label", { className: "text-xs font-semibold text-slate-500 flex justify-between", children: [_jsx("span", { children: "Min Mileage:" }), _jsx("span", { className: "text-brand-600 font-bold", children: filterMinMileage ? `${filterMinMileage} km/l` : 'Any' })] }), _jsx("input", { type: "range", min: 10, max: 25, step: 1, value: filterMinMileage || '10', onChange: (e) => setFilterMinMileage(e.target.value === '10' ? '' : e.target.value), className: "w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-brand-600" }), _jsxs("div", { className: "flex justify-between text-[9px] text-slate-400", children: [_jsx("span", { children: "Any (10 km/l)" }), _jsx("span", { children: "25 km/l" })] })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Engine Performance" }), _jsx("div", { className: "grid grid-cols-2 gap-1.5", children: [
                                            { value: 'Any', label: 'Any' },
                                            { value: 'Eco', label: 'Eco (<1.2L)' },
                                            { value: 'Medium', label: 'Standard (1.2-1.6L)' },
                                            { value: 'High', label: 'Sports (>1.6L)' }
                                        ].map((perf) => (_jsx("button", { onClick: () => setFilterPerformance(perf.value), className: `px-1.5 py-1.5 rounded-lg text-[10px] font-semibold border transition text-center ${filterPerformance === perf.value
                                                ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                : 'border-slate-200 bg-white text-slate-660'}`, children: perf.label }, perf.value))) })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Price Bounds (INR)" }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "number", placeholder: "Min", min: "0", value: filterMinPrice, onChange: (e) => setFilterMinPrice(e.target.value), className: "w-1/2 bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none focus:border-brand-500" }), _jsx("span", { className: "text-slate-450", children: "-" }), _jsx("input", { type: "number", placeholder: "Max", min: "0", value: filterMaxPrice, onChange: (e) => setFilterMaxPrice(e.target.value), className: "w-1/2 bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none focus:border-brand-500" })] }), priceError && (_jsxs("div", { className: "text-[10px] text-red-500 font-semibold mt-1", children: ["\u26A0\uFE0F ", priceError] }))] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs font-semibold text-slate-500", children: "Sort By" }), _jsxs("select", { value: sortBy, onChange: (e) => setSortBy(e.target.value), className: "w-full bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs text-slate-800 focus:outline-none", children: [_jsx("option", { value: "price", children: "Price" }), _jsx("option", { value: "safetyRating", children: "Safety Rating" }), _jsx("option", { value: "mileage", children: "Mileage" })] }), _jsxs("div", { className: "flex space-x-1.5 mt-1.5", children: [_jsx("button", { onClick: () => setSortOrder('asc'), className: `flex-1 py-1.5 rounded-lg text-xs font-semibold border transition ${sortOrder === 'asc'
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660'}`, children: "Low to High" }), _jsx("button", { onClick: () => setSortOrder('desc'), className: `flex-1 py-1.5 rounded-lg text-xs font-semibold border transition ${sortOrder === 'desc'
                                                    ? 'bg-brand-50 border-brand-200 text-brand-600'
                                                    : 'border-slate-200 bg-white text-slate-660'}`, children: "High to Low" })] })] })] }), _jsx("div", { className: "pt-3 border-t border-slate-100 shrink-0 bg-white z-10", children: _jsxs("button", { onClick: applyFilters, className: "w-full py-2.5 rounded-lg bg-brand-600 hover:bg-brand-500 text-white font-bold text-xs transition flex items-center justify-center space-x-1.5 shadow-sm", children: [_jsx(Search, { className: "h-3.5 w-3.5" }), _jsx("span", { children: "Apply Filters" })] }) })] }), _jsxs("div", { className: "lg:col-span-3 flex flex-col", children: [_jsx("div", { className: "sticky top-16 bg-slate-50/95 backdrop-blur-sm z-30 pb-4 pt-1 border-b border-slate-200", children: _jsxs("form", { onSubmit: handleSearchSubmit, className: "flex space-x-2", children: [_jsxs("div", { className: "relative flex-grow", children: [_jsx(Search, { className: "absolute left-3 top-3.5 h-4 w-4 text-slate-400" }), _jsx("input", { type: "text", placeholder: "Search by keywords (e.g. Swift, Nexon, Sedan)...", value: searchKeyword, onChange: (e) => setSearchKeyword(e.target.value), className: "w-full bg-white border border-slate-200 rounded-lg pl-9 pr-4 py-2.5 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500" })] }), _jsx("button", { type: "submit", className: "px-6 py-2.5 rounded-lg bg-brand-600 hover:bg-brand-500 text-white font-bold text-sm transition flex items-center space-x-2 shadow-sm", children: _jsx("span", { children: "Find" }) })] }) }), _jsxs("div", { className: "flex flex-col h-[calc(100vh-200px)] mt-4 justify-between", children: [_jsxs("div", { className: "overflow-y-auto pr-1 space-y-4 flex-grow custom-scrollbar", children: [_jsx("div", { className: "flex justify-between items-center text-xs text-slate-500 mb-2", children: _jsxs("span", { children: ["Displaying ", _jsx("b", { children: cars.length }), " of ", _jsx("b", { children: totalCars }), " vehicles matches"] }) }), loadingCars ? (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6", children: [1, 2, 3].map((i) => (_jsx("div", { className: "glass-card animate-pulse h-80 w-full" }, i))) })) : cars.length === 0 ? (_jsxs("div", { className: "glass-panel p-12 text-center space-y-3", children: [_jsx(AlertCircle, { className: "h-10 w-10 text-brand-600 mx-auto" }), _jsx("h4", { className: "font-bold text-slate-800", children: "No vehicles found" }), _jsx("p", { className: "text-sm text-slate-500", children: "Try modifying your filter parameters or search terms." })] })) : (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 pb-4", children: cars.map((car) => (_jsxs("div", { onClick: () => openCarDetails(car), className: "glass-card overflow-hidden hover-scale flex flex-col justify-between cursor-pointer", children: [_jsx("img", { src: car.images?.[0] ||
                                                        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80', alt: car.model, className: "h-44 w-full object-cover border-b border-slate-100" }), _jsxs("div", { className: "p-4 space-y-3 flex-grow flex flex-col justify-between", children: [_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx("span", { className: "text-xs font-bold text-brand-600 uppercase tracking-wide", children: car.make }), _jsxs("span", { className: "flex items-center text-xs text-amber-600 bg-amber-50 border border-amber-100 px-1.5 py-0.5 rounded font-medium", children: [_jsx(Star, { className: "h-3 w-3 fill-amber-500 text-amber-500 mr-0.5" }), car.safetyRating, " Star"] })] }), _jsxs("h4", { className: "font-bold text-base text-slate-800", children: [car.model, ' ', _jsxs("span", { className: "text-xs font-normal text-slate-500", children: ["(", car.variant, ")"] })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 py-2 border-y border-slate-100 my-2 text-xs text-slate-555", children: [_jsxs("span", { children: ["\u26FD ", car.fuelType] }), _jsxs("span", { children: ["\u2699\uFE0F ", car.transmission] }), _jsxs("span", { children: ["\uD83D\uDE97 ", car.bodyType] }), _jsxs("span", { children: ["\uD83D\uDCC8 ", car.mileage, " km/l"] })] }), _jsxs("div", { className: "flex items-center justify-between pt-2", children: [_jsx("span", { className: "font-extrabold text-sm text-brand-600", children: formatCurrency(car.price) }), renderCarActions(car)] })] })] }, car._id))) }))] }), cars.length > 0 && (_jsxs("div", { className: "flex items-center justify-between py-3 border-t border-slate-200 bg-slate-50/95 backdrop-blur-sm z-20 mt-2 shrink-0", children: [_jsx("button", { onClick: () => setCurrentPage((prev) => Math.max(prev - 1, 1)), disabled: currentPage === 1, className: "px-4 py-2 text-xs font-semibold rounded-lg bg-white border border-slate-200 disabled:opacity-40 disabled:cursor-not-allowed hover:bg-slate-50 text-slate-600 transition shadow-sm", children: "Previous Page" }), _jsxs("span", { className: "text-xs font-bold text-slate-650 bg-white border border-slate-200 px-3 py-1.5 rounded-lg shadow-sm", children: ["Page ", currentPage] }), _jsx("button", { onClick: () => setCurrentPage((prev) => prev + 1), disabled: !hasNextPage, className: "px-4 py-2 text-xs font-semibold rounded-lg bg-white border border-slate-200 disabled:opacity-40 disabled:cursor-not-allowed hover:bg-slate-50 text-slate-600 transition shadow-sm", children: "Next Page" })] }))] })] })] }));
};
//# sourceMappingURL=BrowseCars.js.map