import React from 'react';
interface CarContextType {
    activeTab: 'home' | 'search' | 'compare' | 'wishlist';
    setActiveTab: (tab: 'home' | 'search' | 'compare' | 'wishlist') => void;
    cars: any[];
    totalCars: number;
    currentPage: number;
    setCurrentPage: React.Dispatch<React.SetStateAction<number>>;
    hasNextPage: boolean;
    loadingCars: boolean;
    searchKeyword: string;
    setSearchKeyword: (keyword: string) => void;
    filterBrand: string;
    setFilterBrand: (brand: string) => void;
    filterFuel: string;
    setFilterFuel: (fuel: string) => void;
    filterTransmission: string;
    setFilterTransmission: (transmission: string) => void;
    filterMinPrice: string;
    setFilterMinPrice: (minPrice: string) => void;
    filterMaxPrice: string;
    setFilterMaxPrice: (maxPrice: string) => void;
    filterPerformance: string;
    setFilterPerformance: (performance: string) => void;
    sortBy: string;
    setSortBy: (sortBy: string) => void;
    sortOrder: 'asc' | 'desc';
    setSortOrder: (order: 'asc' | 'desc') => void;
    priceError: string;
    brands: string[];
    fuelTypes: string[];
    transmissions: string[];
    bodyTypes: string[];
    searchMode: 'catalog' | 'advisor';
    setSearchMode: (mode: 'catalog' | 'advisor') => void;
    wizardBudget: number;
    setWizardBudget: (budget: number) => void;
    wizardFamilySize: number;
    setWizardFamilySize: (size: number) => void;
    wizardFuel: string;
    setWizardFuel: (fuel: string) => void;
    wizardTransmission: string;
    setWizardTransmission: (transmission: string) => void;
    wizardDailyDistance: number;
    setWizardDailyDistance: (distance: number) => void;
    wizardPriority: string;
    setWizardPriority: (priority: string) => void;
    wizardBrandPref: string;
    setWizardBrandPref: (brand: string) => void;
    smartRecommendations: any[];
    setSmartRecommendations: (recs: any[]) => void;
    advisorExplanation: string;
    setAdvisorExplanation: (exp: string) => void;
    advisorLoading: boolean;
    consultationHistory: any[];
    selectedForCompare: any[];
    setSelectedForCompare: React.Dispatch<React.SetStateAction<any[]>>;
    compareData: any;
    loadingCompare: boolean;
    handleToggleSelectCompare: (car: any) => void;
    triggerComparisonFetch: () => Promise<void>;
    wishlistIds: string[];
    wishlistCars: any[];
    handleToggleWishlist: (carId: string) => Promise<void>;
    selectedCar: any;
    setSelectedCar: (car: any) => void;
    carReviews: any[];
    reviewsLoading: boolean;
    reviewRating: number;
    setReviewRating: (rating: number) => void;
    reviewText: string;
    setReviewText: (text: string) => void;
    reviewSubmitting: boolean;
    reviewError: string;
    openCarDetails: (car: any) => void;
    closeCarDetails: () => void;
    handleSubmitReview: (e: React.FormEvent) => Promise<void>;
    handleDeleteReview: (reviewId: string) => Promise<void>;
    handleGenerateRecommendations: (e: React.FormEvent) => Promise<void>;
    fetchCars: () => Promise<void>;
    applyFilters: () => void;
    resetFilters: () => void;
}
export declare const CarProvider: React.FC<{
    children: React.ReactNode;
}>;
export declare const useCars: () => CarContextType;
export {};
